[package]
name = "rust-lightning-bitcoinrpc"
version = "0.0.1"
authors = ["Matt Corallo <git@bluematt.me>"]
edition = "2018"

[dependencies]
lightning-net-tokio = { "path" = "./net" }
tokio = { version = "0.2", features = ["io-std", "tcp"] }
